export const timeValues = () => {
  const n = ["00", "15", "30", "45"];
  const m = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
  ];
  let timeSlots = [];

  for (const [i, iValue] of m.entries()) {
    for (const [j, jValue] of n.entries()) {
      timeSlots.push(`${iValue}:${jValue}`);
    }
  }

  return timeSlots;
};

export const indices = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
];


export const timeIntervals = {
    '0': { category: '', activity: '', note: '' },
    '1': { category: '', activity: '', note: '' },
    '2': { category: '', activity: '', note: '' },
    '3': { category: '', activity: '', note: '' },
    '4': { category: '', activity: '', note: '' },
    '5': { category: '', activity: '', note: '' },
    '6': { category: '', activity: '', note: '' },
    '7': { category: '', activity: '', note: '' },
    '8': { category: '', activity: '', note: '' },
    '9': { category: '', activity: '', note: '' },
    '10': { category: '', activity: '', note: '' },
    '11': { category: '', activity: '', note: '' },
    '12': { category: '', activity: '', note: '' },
    '13': { category: '', activity: '', note: '' },
    '14': { category: '', activity: '', note: '' },
    '15': { category: '', activity: '', note: '' },
    '16': { category: '', activity: '', note: '' },
    '17': { category: '', activity: '', note: '' },
    '18': { category: '', activity: '', note: '' },
    '19': { category: '', activity: '', note: '' },
    '20': { category: '', activity: '', note: '' },
    '21': { category: '', activity: '', note: '' },
    '22': { category: '', activity: '', note: '' },
    '23': { category: '', activity: '', note: '' },
    '24': { category: '', activity: '', note: '' },
    '25': { category: '', activity: '', note: '' },
    '26': { category: '', activity: '', note: '' },
    '27': { category: '', activity: '', note: '' },
    '28': { category: '', activity: '', note: '' },
    '29': { category: '', activity: '', note: '' },
    '30': { category: '', activity: '', note: '' },
    '31': { category: '', activity: '', note: '' },
    '32': { category: '', activity: '', note: '' },
    '33': { category: '', activity: '', note: '' },
    '34': { category: '', activity: '', note: '' },
    '35': { category: '', activity: '', note: '' },
    '36': { category: '', activity: '', note: '' },
    '37': { category: '', activity: '', note: '' },
    '38': { category: '', activity: '', note: '' },
    '39': { category: '', activity: '', note: '' },
    '40': { category: '', activity: '', note: '' },
    '41': { category: '', activity: '', note: '' },
    '42': { category: '', activity: '', note: '' },
    '43': { category: '', activity: '', note: '' },
    '44': { category: '', activity: '', note: '' },
    '45': { category: '', activity: '', note: '' },
    '46': { category: '', activity: '', note: '' },
    '47': { category: '', activity: '', note: '' },
    '48': { category: '', activity: '', note: '' },
    '49': { category: '', activity: '', note: '' },
    '50': { category: '', activity: '', note: '' },
    '51': { category: '', activity: '', note: '' },
    '52': { category: '', activity: '', note: '' },
    '53': { category: '', activity: '', note: '' },
    '54': { category: '', activity: '', note: '' },
    '55': { category: '', activity: '', note: '' },
    '56': { category: '', activity: '', note: '' },
    '57': { category: '', activity: '', note: '' },
    '58': { category: '', activity: '', note: '' },
    '59': { category: '', activity: '', note: '' },
    '60': { category: '', activity: '', note: '' },
    '61': { category: '', activity: '', note: '' },
    '62': { category: '', activity: '', note: '' },
    '63': { category: '', activity: '', note: '' },
    '64': { category: '', activity: '', note: '' },
    '65': { category: '', activity: '', note: '' },
    '66': { category: '', activity: '', note: '' },
    '67': { category: '', activity: '', note: '' },
    '68': { category: '', activity: '', note: '' },
    '69': { category: '', activity: '', note: '' },
    '70': { category: '', activity: '', note: '' },
    '71': { category: '', activity: '', note: '' },
    '72': { category: '', activity: '', note: '' },
    '73': { category: '', activity: '', note: '' },
    '74': { category: '', activity: '', note: '' },
    '75': { category: '', activity: '', note: '' },
    '76': { category: '', activity: '', note: '' },
    '77': { category: '', activity: '', note: '' },
    '78': { category: '', activity: '', note: '' },
    '79': { category: '', activity: '', note: '' },
    '80': { category: '', activity: '', note: '' },
    '81': { category: '', activity: '', note: '' },
    '82': { category: '', activity: '', note: '' },
    '83': { category: '', activity: '', note: '' },
    '84': { category: '', activity: '', note: '' },
    '85': { category: '', activity: '', note: '' },
    '86': { category: '', activity: '', note: '' },
    '87': { category: '', activity: '', note: '' },
    '88': { category: '', activity: '', note: '' },
    '89': { category: '', activity: '', note: '' },
    '90': { category: '', activity: '', note: '' },
    '91': { category: '', activity: '', note: '' },
    '92': { category: '', activity: '', note: '' },
    '93': { category: '', activity: '', note: '' },
    '94': { category: '', activity: '', note: '' },
    '95': { category: '', activity: '', note: '' }
}

export const weekDays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

export const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]